import { GENERATED_DIR, EXPORT_DIR, SAMPLES_DIR } from '../config/paths.js';
import { readJson, writeJson } from '../utils/fs.js';
import { resolveDestinationToken, crosswalkByCoreId } from '../config/destination-crosswalk.js';
import { buildTomTomNodeIndex, lookupTomTomNode, type TomTomNodeIndex } from '../compile/build-location-coordinate-index.js';
import type { TomTomGeotagIndex, TomTomNodeEntry } from '../domain/output.js';
import type { BaseEntity } from '../domain/common.js';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

/**
 * E5 — geo feed export for jvto-web: a real coordinate + Schema.org `geo` payload,
 * built entirely from the TomTom-verified node index (28-tomtom-geotag-index.json)
 * so jvto-web can stop rendering a placeholder map / emitting no structured data.
 *
 * Sources (read-only, never regenerated by this module):
 *  - generated/itinerary-intelligence/28-tomtom-geotag-index.json  (verified node coordinates)
 *  - generated/itinerary-intelligence/22-destinations-master.json (static destination fixture: id/name)
 *  - generated/itinerary-intelligence/agent-contract/standard-route-truth.json (per-package route_sequence place names)
 *
 * Contract: never invent a coordinate. Any destination or route node that cannot be
 * joined to a verified TomTom node is dropped from the emitted array and recorded in
 * `missing_coordinates` instead.
 */

// ---------------------------------------------------------------------------
// name -> node_id joins (small, bounded, hand-verified — NOT auto-slugified against
// the crosswalk coreId, because 3 of 8 crosswalk coreIds ('malang_batu',
// 'surabaya_city', 'bali_ketapang') don't textually match their tomtom node_id
// ('malang', 'surabaya', 'bali'). A wrong automated match here would silently mis-join
// a destination's coordinate, which is worse than a reported gap.
const CORE_ID_TO_NODE_ID: Record<string, string> = {
  bromo: 'bromo',
  ijen: 'ijen',
  tumpak_sewu: 'tumpak_sewu',
  madakaripura: 'madakaripura',
  papuma: 'papuma',
  malang_batu: 'malang',
  surabaya_city: 'surabaya',
  bali_ketapang: 'bali'
};

// standard-route-truth.json route_sequence.value entries are short display labels
// (produced by build-agent-contract.mjs's own token->label map), not node_ids or
// crosswalk names. Inverted here for the same 9 tokens that map ever appears.
const ROUTE_LABEL_TO_NODE_ID: Record<string, string> = {
  Bali: 'bali',
  Surabaya: 'surabaya',
  Bromo: 'bromo',
  Ijen: 'ijen',
  Madakaripura: 'madakaripura',
  Papuma: 'papuma',
  'Tumpak Sewu': 'tumpak_sewu',
  Malang: 'malang',
  'Taman Safari Prigen': 'taman_safari_prigen',
  'Bali / Ketapang': 'bali'
};

function slugifyToken(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

/**
 * Resolve a 22-destinations-master.json destination name to its crosswalk core id.
 * Tries the raw name first, then a couple of documented suffix/prefix strips for
 * names that don't literally appear in DESTINATION_CROSSWALK's alias lists (e.g.
 * master calls it "Mount Ijen"; the crosswalk's aliases for `ijen` are
 * ['ijen', 'kawah ijen', 'ijen crater'] — deliberately NOT 'mount ijen', since jvto-web's
 * real page/slug is ijen-crater, not mount-ijen). Returns null (a genuine gap) when
 * no crosswalk entry exists at all (e.g. Taman Safari Prigen, Coffee & Cocoa Technopark).
 */
function resolveCoreIdForMasterName(name: string): string | null {
  const direct = resolveDestinationToken(name);
  if (direct) return direct;
  const stripped = name
    .replace(/^Mount\s+/i, '')
    .replace(/\s+(Waterfall|Beach|City|Area)$/i, '')
    .trim();
  if (stripped !== name) {
    const viaStrip = resolveDestinationToken(stripped);
    if (viaStrip) return viaStrip;
  }
  return null;
}

interface DestinationsMasterFile {
  destinations: Array<{ id: number; name: string; [key: string]: unknown }>;
}

interface StandardRouteTruthFile {
  packages: Array<{ package_key: string; route_sequence: { value: string[] } }>;
}

export interface GeoFeedDestination {
  id: string;
  name: string;
  lat: number;
  lng: number;
  /**
   * Carries the coordinate's real per-node provenance from 28-tomtom-geotag-index.json.
   * 'verified_tomtom_api' = confirmed via a live TomTom API call; 'seed_approximation' =
   * a researched/estimated coordinate, not TomTom-verified. Never collapse this to a
   * blanket "verified" — several of the 5 minimum-coverage destinations (Bromo, Ijen,
   * Tumpak Sewu, Madakaripura, Taman Safari Prigen) are currently seed_approximation.
   */
  geo_confidence: 'verified_tomtom_api' | 'seed_approximation';
  geo_source: string;
  schema_org: {
    '@type': 'TouristAttraction';
    name: string;
    url: string | null;
    geo: { '@type': 'GeoCoordinates'; latitude: number; longitude: number };
    /**
     * Deliberate, non-accidental addition for Ijen: a known outstanding
     * governance/SEO item (blue-fire/sulfur-gas hazard disclosure), added per the
     * E5 execution plan — not a placeholder or a mistake.
     */
    hazardousSubstance?: string;
  };
}

export interface GeoFeedRouteNode {
  name: string;
  lat: number;
  lng: number;
  sequence: number;
  /** Same real per-node provenance as GeoFeedDestination.geo_confidence — never assume verified. */
  geo_confidence: 'verified_tomtom_api' | 'seed_approximation';
}

export interface GeoFeedRoute {
  package_id: string;
  nodes: GeoFeedRouteNode[];
}

export interface GeoFeedMissingCoordinate {
  context: 'destination' | 'route_node';
  ref: string;
  reason: string;
}

export interface GeoFeed extends BaseEntity {
  generated_at: string;
  destinations: GeoFeedDestination[];
  routes: GeoFeedRoute[];
  missing_coordinates: GeoFeedMissingCoordinate[];
}

function loadNodeIndex(geotagIndex: TomTomGeotagIndex): TomTomNodeIndex {
  return buildTomTomNodeIndex(geotagIndex.nodes as TomTomNodeEntry[]);
}

function buildDestinations(
  master: DestinationsMasterFile,
  nodeIndex: TomTomNodeIndex,
  missing: GeoFeedMissingCoordinate[]
): GeoFeedDestination[] {
  const out: GeoFeedDestination[] = [];

  for (const d of master.destinations) {
    const coreId = resolveCoreIdForMasterName(d.name);
    const crosswalkEntry = coreId ? crosswalkByCoreId(coreId) : null;
    const nodeId = coreId ? (CORE_ID_TO_NODE_ID[coreId] ?? slugifyToken(coreId)) : slugifyToken(d.name);
    const node = lookupTomTomNode(nodeIndex, nodeId);

    if (!node) {
      missing.push({
        context: 'destination',
        ref: `${d.id}:${d.name}`,
        reason: coreId
          ? `no verified TomTom node for node_id "${nodeId}" (core id "${coreId}")`
          : `no destination-crosswalk entry and no verified TomTom node for node_id "${nodeId}"`
      });
      continue;
    }

    // Prefer the jvto-web crosswalk's display name over the raw master name: the
    // master fixture still calls destination id 2 "Mount Ijen", but jvto-web's real
    // page/slug identity is "Ijen Crater" (slug ijen-crater) — using the master name
    // here would re-introduce the mount-ijen naming bug into this feed's own output.
    const displayName = crosswalkEntry?.name ?? d.name;
    const url = crosswalkEntry?.slug ? `/destinations/${crosswalkEntry.slug}` : null;

    const schema_org: GeoFeedDestination['schema_org'] = {
      '@type': 'TouristAttraction',
      name: displayName,
      url,
      geo: { '@type': 'GeoCoordinates', latitude: node.lat, longitude: node.lng }
    };
    if (coreId === 'ijen') {
      schema_org.hazardousSubstance = 'sulfur dioxide gas';
    }

    out.push({
      id: coreId ?? slugifyToken(d.name),
      name: displayName,
      lat: node.lat,
      lng: node.lng,
      geo_confidence: node.confidence,
      geo_source: node.geo_source,
      schema_org
    });
  }

  return out;
}

function buildRoutes(
  routeTruth: StandardRouteTruthFile,
  nodeIndex: TomTomNodeIndex,
  missing: GeoFeedMissingCoordinate[]
): GeoFeedRoute[] {
  return routeTruth.packages.map((pkg) => {
    const nodes: GeoFeedRouteNode[] = [];
    pkg.route_sequence.value.forEach((placeName, i) => {
      const nodeId = ROUTE_LABEL_TO_NODE_ID[placeName] ?? slugifyToken(placeName);
      const node = lookupTomTomNode(nodeIndex, nodeId);
      if (!node) {
        missing.push({
          context: 'route_node',
          ref: `${pkg.package_key}:${placeName}`,
          reason: `no verified TomTom node for node_id "${nodeId}"`
        });
        return; // do not guess a coordinate — sequence numbers may show a gap
      }
      nodes.push({ name: placeName, lat: node.lat, lng: node.lng, sequence: i + 1, geo_confidence: node.confidence });
    });
    return { package_id: pkg.package_key, nodes };
  });
}

export async function buildGeoFeed(): Promise<GeoFeed> {
  const geotagIndexFile = await readJson<TomTomGeotagIndex[]>(`${GENERATED_DIR}/28-tomtom-geotag-index.json`);
  const geotagIndex = geotagIndexFile[0];
  const master = await readJson<DestinationsMasterFile>(`${GENERATED_DIR}/22-destinations-master.json`);
  const routeTruth = await readJson<StandardRouteTruthFile>(`${GENERATED_DIR}/agent-contract/standard-route-truth.json`);

  const nodeIndex = loadNodeIndex(geotagIndex);
  const missing_coordinates: GeoFeedMissingCoordinate[] = [];

  const destinations = buildDestinations(master, nodeIndex, missing_coordinates);
  const routes = buildRoutes(routeTruth, nodeIndex, missing_coordinates);

  return {
    id: 'geo_feed',
    label: 'jvto-web geo feed: destination + route-node coordinates and Schema.org geo blocks',
    status: 'active',
    // Feed-level confidence reflects that coordinates are a MIX of
    // verified_tomtom_api and seed_approximation nodes (see each destination's/
    // route node's own geo_confidence for the real per-node truth) — not a
    // blanket claim that every coordinate here is TomTom-verified.
    confidence: 'inferred',
    source_trace: [
      {
        source: 'tomtom',
        ref: `${GENERATED_DIR}/28-tomtom-geotag-index.json`,
        field: 'nodes[].lat,lng,confidence,geo_source',
        confidence: 'inferred'
      },
      {
        source: 'generated',
        ref: `${GENERATED_DIR}/22-destinations-master.json`,
        field: 'destinations[].id,name',
        confidence: 'verified'
      },
      {
        source: 'generated',
        ref: `${GENERATED_DIR}/agent-contract/standard-route-truth.json`,
        field: 'packages[].route_sequence.value',
        confidence: 'verified'
      }
    ],
    generated_at: 'manual_seed_deterministic',
    destinations,
    routes,
    missing_coordinates
  };
}

const OUTPUT_PATH = `${EXPORT_DIR}/page-payload/output/geo-feed.json`;
export const GEO_FEED_SAMPLE_PATH = `${EXPORT_DIR}/page-payload/${SAMPLES_DIR}/geo-feed.sample.json`;

async function main(): Promise<void> {
  const feed = await buildGeoFeed();
  await writeJson(OUTPUT_PATH, feed);
  console.log(`geo-feed: wrote ${OUTPUT_PATH}`);
  console.log(`geo-feed: ${feed.destinations.length} destinations, ${feed.routes.length} routes`);
  if (feed.missing_coordinates.length === 0) {
    console.log('geo-feed: missing_coordinates: none');
  } else {
    console.log(`geo-feed: missing_coordinates (${feed.missing_coordinates.length}):`);
    for (const m of feed.missing_coordinates) {
      console.log(`  - [${m.context}] ${m.ref} — ${m.reason}`);
    }
  }
}

// Run only when executed directly (tsx src/export/geo-feed.ts), not when imported by tests.
// Compare via fileURLToPath/resolve (not a raw `file://${path}` string), since on
// Windows process.argv[1] is a filesystem path (D:\...) while import.meta.url is a
// file URL (file:///D:/...) with different separators/casing — a literal string
// comparison never matches there, silently skipping main() and writing no output.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
