import type { CostComponent } from '../domain/cost.js';

export function buildCostComponents(): CostComponent[] {
  return [
    {
      id: 'vehicle_private_car_day',
      label: 'Private vehicle day cost',
      status: 'active',
      confidence: 'manual_seed',
      category: 'transport_day_cost',
      unit: 'per_day',
      applies_when: ['private tour', 'vehicle assigned'],
      customer_visible: false,
      formula: 'vehicle_day_rate * tour_days',
      default_rate_idr: null,
      channel_behavior: ['JVTO', 'KLOOK', 'TWT', 'CUSTOM'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'bromo_jeep',
      label: 'Bromo jeep',
      status: 'active',
      confidence: 'manual_seed',
      category: 'jeep',
      unit: 'per_vehicle',
      applies_when: ['destination includes Bromo sunrise'],
      customer_visible: 'included_in_package',
      formula: 'jeep_unit_price * jeep_count',
      default_rate_idr: null,
      channel_behavior: ['usually_included'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'ijen_medical_check',
      label: 'Ijen medical check',
      status: 'active',
      confidence: 'manual_seed',
      category: 'health_check',
      unit: 'per_person',
      applies_when: ['destination includes Ijen'],
      customer_visible: true,
      formula: 'medical_check_rate * pax',
      default_rate_idr: null,
      channel_behavior: ['required_for_ijen'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'ijen_local_guide',
      label: 'Ijen local guide',
      status: 'active',
      confidence: 'manual_seed',
      category: 'local_guide_cost',
      unit: 'per_group',
      applies_when: ['destination includes Ijen'],
      customer_visible: 'included_in_package',
      formula: 'ijen_local_guide_rate * guide_count',
      default_rate_idr: null,
      channel_behavior: ['included_in_private_package'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'madakaripura_local_guide',
      label: 'Madakaripura local guide',
      status: 'active',
      confidence: 'manual_seed',
      category: 'local_guide_cost',
      unit: 'per_group',
      applies_when: ['destination includes Madakaripura'],
      customer_visible: 'included_in_package',
      formula: 'madakaripura_local_guide_rate * group_count',
      default_rate_idr: null,
      channel_behavior: ['managed_by_local_organization'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'bali_dropoff_after_ketapang',
      label: 'Bali dropoff after Ketapang',
      status: 'active',
      confidence: 'manual_seed',
      category: 'transport_extra_dropoff',
      unit: 'formula',
      applies_when: ['standard package ends at Ketapang', 'customer requests Bali hotel dropoff'],
      customer_visible: true,
      formula: 'bali_transfer_rate + ferry_or_handoff_cost',
      default_rate_idr: null,
      channel_behavior: ['usually_additional_cost'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'driver_cost',
      label: 'Driver cost',
      status: 'active',
      confidence: 'manual_seed',
      category: 'driver_cost',
      unit: 'per_day',
      applies_when: ['vehicle assigned', 'private overland route'],
      customer_visible: false,
      formula: 'driver_day_rate * assigned_days',
      default_rate_idr: null,
      channel_behavior: ['internal_cost_component'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'escort_cost',
      label: 'Escort cost',
      status: 'active',
      confidence: 'manual_seed',
      category: 'escort_cost',
      unit: 'per_day',
      applies_when: ['tour escort assigned'],
      customer_visible: false,
      formula: 'escort_day_rate * assigned_days',
      default_rate_idr: null,
      channel_behavior: ['optional_internal_cost_component'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'destination_ticket',
      label: 'Destination ticket',
      status: 'active',
      confidence: 'manual_seed',
      category: 'destination_ticket',
      unit: 'per_person',
      applies_when: ['destination requires ticket'],
      customer_visible: 'included_in_package',
      formula: 'ticket_rate * pax',
      default_rate_idr: null,
      channel_behavior: ['rate_varies_by_destination_and_day_type'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'hotel_room',
      label: 'Hotel room',
      status: 'active',
      confidence: 'manual_seed',
      category: 'hotel_room',
      unit: 'per_room',
      applies_when: ['overnight included', 'hotel category selected'],
      customer_visible: 'included_in_package',
      formula: 'room_rate * room_count * nights',
      default_rate_idr: null,
      channel_behavior: ['requires_verified_hotel_rate_export'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'hotel_breakfast_or_takeaway',
      label: 'Hotel breakfast or takeaway breakfast',
      status: 'active',
      confidence: 'manual_seed',
      category: 'hotel_meal',
      unit: 'per_person',
      applies_when: ['hotel breakfast included or replaced by takeaway due early departure'],
      customer_visible: 'included_in_package',
      formula: 'hotel_meal_rate * pax',
      default_rate_idr: null,
      channel_behavior: ['depends_on_hotel_policy'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'restaurant_meal',
      label: 'Restaurant meal',
      status: 'active',
      confidence: 'manual_seed',
      category: 'restaurant_meal',
      unit: 'per_person',
      applies_when: ['included lunch or dinner is arranged outside hotel'],
      customer_visible: 'included_in_package',
      formula: 'meal_rate * pax',
      default_rate_idr: null,
      channel_behavior: ['some_meals_are_own_expense_unless_stated'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'gas_mask',
      label: 'Ijen gas mask or equipment',
      status: 'active',
      confidence: 'manual_seed',
      category: 'equipment',
      unit: 'per_person',
      applies_when: ['destination includes Ijen'],
      customer_visible: 'included_in_package',
      formula: 'equipment_rate * pax',
      default_rate_idr: null,
      channel_behavior: ['required_for_ijen'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'ferry_ticket',
      label: 'Ferry ticket',
      status: 'active',
      confidence: 'manual_seed',
      category: 'ferry',
      unit: 'per_person',
      applies_when: ['Ketapang to Gilimanuk crossing', 'Bali transfer requested'],
      customer_visible: true,
      formula: 'ferry_rate * pax or vehicle_crossing_rate if vehicle crosses',
      default_rate_idr: null,
      channel_behavior: ['requires_transfer_model_decision'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'addon_activity',
      label: 'Add-on activity',
      status: 'active',
      confidence: 'manual_seed',
      category: 'add_on',
      unit: 'fixed',
      applies_when: ['custom destination or optional activity added'],
      customer_visible: true,
      formula: 'addon_rate based on selected activity and group size',
      default_rate_idr: null,
      channel_behavior: ['quoted_separately_until_verified'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'police_escort',
      label: 'Police escort',
      status: 'draft',
      confidence: 'needs_review',
      category: 'police_escort',
      unit: 'fixed',
      applies_when: ['special operational escort requested or required'],
      customer_visible: false,
      formula: 'requires manual operations approval',
      default_rate_idr: null,
      channel_behavior: ['not_standard_customer_pricing'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'needs_review' }]
    },
    {
      id: 'crew_cash',
      label: 'Crew cash',
      status: 'active',
      confidence: 'manual_seed',
      category: 'crew_cash',
      unit: 'per_group',
      applies_when: ['internal ops cash allocation required'],
      customer_visible: false,
      formula: 'cash_allocation_by_route_and_duration',
      default_rate_idr: null,
      channel_behavior: ['internal_only'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'manual_seed' }]
    },
    {
      id: 'actual_expense_calibration',
      label: 'Actual expense calibration',
      status: 'needs_review',
      confidence: 'needs_review',
      category: 'actual_expense_calibration',
      unit: 'formula',
      applies_when: ['redacted backoffice finance export is available'],
      customer_visible: false,
      formula: 'compare estimated component rates with redacted actual expense summary',
      default_rate_idr: null,
      channel_behavior: ['future_backoffice_ingestion'],
      source_trace: [{ source: 'manual_seed', ref: 'seed/manual-overrides/cost-components.yaml', confidence: 'needs_review' }]
    }
  ];
}
